sudo: false
language: ruby
cache:
  directories:
   - /home/travis/arduino_ci_ide/arduino
   - /home/travis/Arduino/libraries/arduino
script:
   - bundle install
   - bundle exec arduino_ci_remote.rb
after_success:
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
