sudo: false
language: ruby
script:
   - bundle install
   - bundle exec arduino_ci_remote.rb
after_success:
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
